name: Memory Segments Analysis

on:
  push:
    paths:
      - '**.cpp'
      - '**CMakeLists.txt'
      - '.github/workflows/**'
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y binutils cmake g++ grep

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Analyze Segments
        run: cmake --build build --target analyze_segments

      - name: Run Executable
        run: ./build/segments

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: brew install cmake binutils

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Analyze Segments
        run: cmake --build build --target analyze_segments

      - name: Run Executable
        run: ./build/segments

  build-windows-mingw:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MSYS2 and MinGW
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-binutils
            grep
          msystem: MINGW64
          path-type: inherit

      - name: Configure CMake (MinGW)
        shell: msys2 {0}
        run: cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Analyze Segments (MinGW)
        shell: msys2 {0}
        run: cmake --build build --target analyze_segments

      - name: Run Executable (MinGW)
        shell: msys2 {0}
        run: ./build/segments.exe

  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake (MSVC)
        run: cmake -DCMAKE_BUILD_TYPE=Debug -A x64 -S . -B build

      - name: Analyze Segments (MSVC)
        run: cmake --build build --target analyze_segments

      - name: Run Executable (MSVC)
        run: .\build\segments.exe
