name: Build and Analyze Segments

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MinGW (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msys2-path: mingw64
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-binutils mingw-w64-x86_64-cmake
        update: true

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.13

    - name: Clean build directory
      run: rm -rf build
      shell: bash

    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      shell: bash
      env:
        CC: ${{ matrix.os == 'Windows' && 'gcc' || '' }}
        CXX: ${{ matrix.os == 'Windows' && 'g++' || '' }}

    - name: Debug CMake configuration
      run: |
        cat build/CMakeCache.txt | grep CMAKE_BUILD_TYPE
      shell: bash

    - name: Build analyze_segments target
      run: |
        cmake --build build --target analyze_segments --config Release
      shell: bash

    - name: Debug objdump output
      if: runner.os != 'Windows'
      run: |
        if [ -f build/segments ]; then
          objdump -t build/segments || true
        else
          echo "Executable not found"
          ls -R build
        fi
      shell: bash

    - name: Verify Output - Linux/macOS
      if: runner.os != 'Windows'
      run: |
        echo "Checking for executable..."
        if [ -f build/segments ]; then
          echo "Analysis completed by analyze_segments target"
        else
          echo "Error: build/segments not found"
          ls -R build
          exit 1
        fi
      shell: bash

    - name: Verify Output - Windows (MinGW)
      if: runner.os == 'Windows'
      run: |
        echo "Checking for executable..."
        if exist build\segments.exe (
          echo "Analysis completed by analyze_segments target"
        ) else (
          echo "Error: build\segments.exe not found"
          dir build
          exit 1
        )
      shell: cmd
